# Analyzer configuration for barrel_file_lints
# See https://dart.dev/tools/analysis

include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing returns as errors
    missing_return: error
    # Treat TODOs as info (not warnings) since they're intentional in examples
    todo: info
  
  exclude:
    # Test files can use test_ naming convention
    - test/**

linter:
  rules:
    # Error rules
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - valid_regexps

    # Style rules
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_unnecessary_containers
    - avoid_void_async
    - cascade_invocations
    - directives_ordering
    - leading_newlines_in_multiline_strings
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - only_throw_errors
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - prefer_final_fields
    - public_member_api_docs
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - provide_deprecation_message
    - sized_box_for_whitespace
    - use_build_context_synchronously
    - use_super_parameters
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_parenthesis
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_raw_strings
    - use_string_buffers

    # Pub rules
    - package_names
    
    # Public package best practices
    - comment_references
    - deprecated_consistency
    - do_not_use_environment
    - implementation_imports
    - library_annotations
    - library_private_types_in_public_api
    - noop_primitive_operations
    - secure_pubspec_urls
    - type_literal_in_constant_pattern
    - unnecessary_library_directive
    - unreachable_from_main
